spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev?serverTimezone=UTC
    username: root
    password: 7753191
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false